Content of MainWindow now disappear when importing
MossPiglets/Athena pull request #103
Opened 2021-06-09 12:46 UTC by Zofia-Szybalska

2021-06-09 13:39 UTC, Katarzyna-Kadziolka approved these changes

2021-06-09 13:42 UTC, Morasiu requested changes

2021-06-09 13:42 UTC, Morasiu commented on Athena/Athena/MainWindow.xaml.cs
>                  ProgressBarStatus.Visibility = Visibility.Hidden;
Zamiast zmiany tych dwóch za każdym razem  zmień Visibility `ImportGrid`

2021-06-10 06:57 UTC, Morasiu approved these changes

2021-06-11 07:45 UTC, merged