Double clicking author in MainWindow does not causes an error anymore
MossPiglets/Athena pull request #104
Opened 2021-06-10 10:04 UTC by Zofia-Szybalska

2021-06-11 10:40 UTC, Katarzyna-Kadziolka commented on Athena/Athena/MainWindow.xaml.cs
>      }
W sumie może usuń puste linijki w 216 i 218

2021-06-11 10:53 UTC, Morasiu requested changes

2021-06-11 10:53 UTC, Morasiu commented on Athena/Athena/MainWindow.xaml.cs
>              Book book = Mapper.Instance.Map<Book>(BookList.SelectedItem);
Zamiast używać book do warunku. Użyj `BookList.SelectedItem` i przenieś warunek na początek metody

2021-06-14 08:52 UTC, Morasiu approved these changes

2021-06-19 10:09 UTC, Katarzyna-Kadziolka approved these changes

2021-06-19 10:26 UTC, merged