Feature/remove book and return it bug
MossPiglets/Athena pull request #113
Opened 2021-07-10 11:00 UTC by Katarzyna-Kadziolka

2021-07-10 11:21 UTC, Morasiu commented
Chyba lepiej zrobić klasy np. EditBookMessage lub NewBorrowingMessage.

Można zrobić żeby po prostu dziedziczyły z klasy MessageBase, którą zrobisz.

Protip: abstract

2021-07-11 14:23 UTC, Morasiu requested changes

2021-07-11 14:23 UTC, Morasiu commented on Athena/Athena/MainWindow.xaml.cs
> +            var hub = Hub.Instance;
Nie musisz robić zmiennej hub.

2021-07-11 14:52 UTC, Morasiu approved these changes

2021-07-17 08:06 UTC, Zofia-Szybalska approved these changes

2021-07-17 08:38 UTC, merged