Smutny plaster, który Hubert zhejtuje
MossPiglets/Athena pull request #114
Opened 2021-07-17 08:37 UTC by Katarzyna-Kadziolka

2021-07-17 08:43 UTC, Morasiu requested changes

2021-07-17 08:43 UTC, Morasiu commented on Athena/Athena/MainWindow.xaml.cs
> +
Może chociaż jakieś Distinct czy coś?

2021-07-17 08:57 UTC, Katarzyna-Kadziolka commented on Athena/Athena/MainWindow.xaml.cs
> +
Właśnie Dstinct nie wiem czemu nie działa, od tego zaczęłam. Chciałam w pętli wyłapać o co chodzi, ale pętla działa

2021-07-17 09:15 UTC, Morasiu requested changes

2021-07-17 09:15 UTC, Morasiu commented on Athena/Athena/MainWindow.xaml.cs
> +
Możesz sprobować dodać `IEqualityComparer` czy coś do `Author`

2021-07-17 09:15 UTC, Morasiu commented on Athena/Athena/MainWindow.xaml.cs
> +
https://dotnetfiddle.net/BNcWTS

2021-07-18 11:11 UTC, Morasiu approved these changes

2021-07-19 17:59 UTC, Zofia-Szybalska approved these changes

2021-07-20 07:59 UTC, merged