Feature/return date refresh
MossPiglets/Athena pull request #96
Opened 2021-06-07 10:04 UTC by Zofia-Szybalska

2021-06-07 10:34 UTC, Morasiu requested changes

2021-06-07 10:34 UTC, Morasiu commented on Athena/Athena/Windows/BorrowedBooksListWindow.xaml.cs
> +            returnWindow.BookReturned += (sender, e) => Borrowings.Last(b => b.Book.Id == book.Id).ReturnDate = e.Value.ReturnDate;
Tu zmień na `Single()` z `Last()`

2021-06-07 10:34 UTC, Morasiu commented on Athena/Athena/Windows/ReturnBookWindow.xaml.cs
> +        public class EventArgs<Borrowing> : EventArgs
Skąd taka nazwa? Wygląda fajnie. Jeśli gdzieś na necie polecali to spoko, jak nie to zmień nazwę  na `BookReturnedEventArgs`

2021-06-07 11:57 UTC, Zofia-Szybalska commented on Athena/Athena/Windows/BorrowedBooksListWindow.xaml.cs
> +            returnWindow.BookReturned += (sender, e) => Borrowings.Last(b => b.Book.Id == book.Id).ReturnDate = e.Value.ReturnDate;
Single() tutaj powoduje błąd, jeżeli książka była już kiedyś wcześniej wypożyczona

2021-06-07 11:59 UTC, Morasiu commented on Athena/Athena/Windows/BorrowedBooksListWindow.xaml.cs
> +            returnWindow.BookReturned += (sender, e) => Borrowings.Last(b => b.Book.Id == book.Id).ReturnDate = e.Value.ReturnDate;
Aaa... Bo w moim screenshocie było inaczej. Zerknij tam 😎

2021-06-08 07:00 UTC, Morasiu requested changes

2021-06-08 07:00 UTC, Morasiu commented on Athena/Athena/Windows/ReturnBookWindow.xaml.cs
> +        public class BookReturnedEventArgs<Borrowing> : EventArgs
Nie potrzebujesz `<Borrowing>`

2021-06-08 14:05 UTC, Morasiu approved these changes

2021-06-08 17:15 UTC, merged